/**
 * Auto-generated affiliate store config for bebisguiden.
 * Channel: 2065068845 (Adtraction), 3467325 (Addrevenue).
 * Generated by scripts/setup-multistore-cta.mjs from product feeds.
 */

export interface AffiliateStore {
  name: string;
  commission: number;
  network: 'adtraction' | 'addrevenue' | 'awin' | 'direct';
  baseUrl: string;
  searchUrl?: string;
  buildUrl: (targetUrl: string) => string;
}

export const AFFILIATE_STORES: Record<string, AffiliateStore> = {
  'Babyland': {
    name: 'Babyland',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.babyland.se',
    searchUrl: 'https://www.babyland.se/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1066444609&c=2065068845&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Baby V': {
    name: 'Baby V',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.babyv.se',
    searchUrl: 'https://www.babyv.se/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1327902112&c=2065068845&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Jollyroom': {
    name: 'Jollyroom',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.jollyroom.se',
    searchUrl: 'https://www.jollyroom.se/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1222362815&c=2065068845&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Polarn O. Pyret': {
    name: 'Polarn O. Pyret',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.polarnopyret.se',
    searchUrl: 'https://www.polarnopyret.se/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1126522826&c=2065068845&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Stor och Liten': {
    name: 'Stor och Liten',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.storochliten.se',
    searchUrl: 'https://www.storochliten.se/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1060728461&c=2065068845&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Xplora': {
    name: 'Xplora',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.xplora.com',
    searchUrl: 'https://www.xplora.com/?q={q}',
    buildUrl: (t) => `https://track.adtraction.com/t/t?a=1954032100&c=2065068845&p=1&s=&url=${encodeURIComponent(t)}`,
  },
  'Leksaksaffaren': {
    name: 'Leksaksaffaren',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.leksaksaffaren.com',
    searchUrl: 'https://www.leksaksaffaren.com/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=987009&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Litenleker': {
    name: 'Litenleker',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.litenleker.se',
    searchUrl: 'https://www.litenleker.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=985276&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Min-lilla-sotnos': {
    name: 'Min-lilla-sotnos',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.min-lilla-sotnos.se',
    searchUrl: 'https://www.min-lilla-sotnos.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=986377&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Mickiofsweden': {
    name: 'Mickiofsweden',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.mickiofsweden.com',
    searchUrl: 'https://www.mickiofsweden.com/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=984911&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Reirei': {
    name: 'Reirei',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.reirei.se',
    searchUrl: 'https://www.reirei.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=987575&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Summervilleorganic': {
    name: 'Summervilleorganic',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.summervilleorganic.com',
    searchUrl: 'https://www.summervilleorganic.com/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=985585&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Leksakerplus': {
    name: 'Leksakerplus',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.leksakerplus.se',
    searchUrl: 'https://www.leksakerplus.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=985346&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Najell': {
    name: 'Najell',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.najell.com',
    searchUrl: 'https://www.najell.com/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=984973&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Emmaljunga': {
    name: 'Emmaljunga',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.emmaljunga.com',
    searchUrl: 'https://www.emmaljunga.com/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=986001&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Lealillebror': {
    name: 'Lealillebror',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.lealillebror.se',
    searchUrl: 'https://www.lealillebror.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=985469&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Crescentbarnvagnar': {
    name: 'Crescentbarnvagnar',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.crescentbarnvagnar.se',
    searchUrl: 'https://www.crescentbarnvagnar.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=986149&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Babyonline': {
    name: 'Babyonline',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.babyonline.se',
    searchUrl: 'https://www.babyonline.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=987081&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Inovi': {
    name: 'Inovi',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.inovi.se',
    searchUrl: 'https://www.inovi.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=986153&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Nanobebe': {
    name: 'Nanobebe',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.nanobebe.se',
    searchUrl: 'https://www.nanobebe.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=985384&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Inoki': {
    name: 'Inoki',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.inoki.se',
    searchUrl: 'https://www.inoki.se/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=987691&c=3467325&url=${encodeURIComponent(t)}`,
  },
  'Knattis': {
    name: 'Knattis',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.knattis.com',
    searchUrl: 'https://www.knattis.com/?q={q}',
    buildUrl: (t) => `https://addrevenue.io/t?a=986599&c=3467325&url=${encodeURIComponent(t)}`,
  },
};

export function getStore(storeName: string): AffiliateStore | undefined {
  if (!storeName) return undefined;
  const direct = AFFILIATE_STORES[storeName];
  if (direct) return direct;
  const normalized = storeName.trim().toLowerCase();
  for (const [key, store] of Object.entries(AFFILIATE_STORES)) {
    if (key.toLowerCase() === normalized) return store;
    if (store.name.toLowerCase() === normalized) return store;
  }
  return undefined;
}

export function buildSearchDeeplink(storeName: string, query: string): string | undefined {
  const store = getStore(storeName);
  if (!store?.searchUrl) return undefined;
  const targetUrl = store.searchUrl.replace('{q}', encodeURIComponent(query));
  return store.buildUrl(targetUrl);
}

export function buildProductDeeplink(storeName: string, productPageUrl: string): string | undefined {
  const store = getStore(storeName);
  if (!store) return undefined;
  return store.buildUrl(productPageUrl);
}
