/**
 * Auto-generated affiliate store config for bebisguiden.
 * Channel: 2065068845 (Adtraction), 3467325 (Addrevenue).
 * Generated by scripts/setup-multistore-cta.mjs from product feeds.
 */

export interface AffiliateStore {
  name: string;
  commission: number;
  network: 'adtraction' | 'addrevenue' | 'awin' | 'direct';
  baseUrl: string;
  searchUrl?: string;
  /**
   * @deprecated Använd aldrig denna funktion. Bevarad endast för bakåtkompatibilitet.
   * Returnerar alltid undefined så att hallucinerade tracker-URL:er aldrig kan genereras.
   * Använd `resolveTrackedUrl` från `lib/cta-resolver.ts` istället.
   */
  buildUrl: (targetUrl: string) => string | undefined;
}

export const AFFILIATE_STORES: Record<string, AffiliateStore> = {
  'Babyland': {
    name: 'Babyland',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.babyland.se',
    searchUrl: 'https://www.babyland.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Baby V': {
    name: 'Baby V',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.babyv.se',
    searchUrl: 'https://www.babyv.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Jollyroom': {
    name: 'Jollyroom',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.jollyroom.se',
    searchUrl: 'https://www.jollyroom.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Polarn O. Pyret': {
    name: 'Polarn O. Pyret',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.polarnopyret.se',
    searchUrl: 'https://www.polarnopyret.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Stor och Liten': {
    name: 'Stor och Liten',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.storochliten.se',
    searchUrl: 'https://www.storochliten.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Xplora': {
    name: 'Xplora',
    commission: 0.05,
    network: 'adtraction',
    baseUrl: 'https://www.xplora.com',
    searchUrl: 'https://www.xplora.com/?q={q}',
    buildUrl: () => undefined,
  },
  'Leksaksaffaren': {
    name: 'Leksaksaffaren',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.leksaksaffaren.com',
    searchUrl: 'https://www.leksaksaffaren.com/?q={q}',
    buildUrl: () => undefined,
  },
  'Litenleker': {
    name: 'Litenleker',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.litenleker.se',
    searchUrl: 'https://www.litenleker.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Min-lilla-sotnos': {
    name: 'Min-lilla-sotnos',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.min-lilla-sotnos.se',
    searchUrl: 'https://www.min-lilla-sotnos.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Mickiofsweden': {
    name: 'Mickiofsweden',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.mickiofsweden.com',
    searchUrl: 'https://www.mickiofsweden.com/?q={q}',
    buildUrl: () => undefined,
  },
  'Reirei': {
    name: 'Reirei',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.reirei.se',
    searchUrl: 'https://www.reirei.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Summervilleorganic': {
    name: 'Summervilleorganic',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.summervilleorganic.com',
    searchUrl: 'https://www.summervilleorganic.com/?q={q}',
    buildUrl: () => undefined,
  },
  'Leksakerplus': {
    name: 'Leksakerplus',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.leksakerplus.se',
    searchUrl: 'https://www.leksakerplus.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Najell': {
    name: 'Najell',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.najell.com',
    searchUrl: 'https://www.najell.com/?q={q}',
    buildUrl: () => undefined,
  },
  'Emmaljunga': {
    name: 'Emmaljunga',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.emmaljunga.com',
    searchUrl: 'https://www.emmaljunga.com/?q={q}',
    buildUrl: () => undefined,
  },
  'Lealillebror': {
    name: 'Lealillebror',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.lealillebror.se',
    searchUrl: 'https://www.lealillebror.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Crescentbarnvagnar': {
    name: 'Crescentbarnvagnar',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.crescentbarnvagnar.se',
    searchUrl: 'https://www.crescentbarnvagnar.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Babyonline': {
    name: 'Babyonline',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.babyonline.se',
    searchUrl: 'https://www.babyonline.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Inovi': {
    name: 'Inovi',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.inovi.se',
    searchUrl: 'https://www.inovi.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Nanobebe': {
    name: 'Nanobebe',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.nanobebe.se',
    searchUrl: 'https://www.nanobebe.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Inoki': {
    name: 'Inoki',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.inoki.se',
    searchUrl: 'https://www.inoki.se/?q={q}',
    buildUrl: () => undefined,
  },
  'Knattis': {
    name: 'Knattis',
    commission: 0.05,
    network: 'addrevenue',
    baseUrl: 'https://www.knattis.com',
    searchUrl: 'https://www.knattis.com/?q={q}',
    buildUrl: () => undefined,
  },
};

export function getStore(storeName: string): AffiliateStore | undefined {
  if (!storeName) return undefined;
  const direct = AFFILIATE_STORES[storeName];
  if (direct) return direct;
  const normalized = storeName.trim().toLowerCase();
  for (const [key, store] of Object.entries(AFFILIATE_STORES)) {
    if (key.toLowerCase() === normalized) return store;
    if (store.name.toLowerCase() === normalized) return store;
  }
  return undefined;
}

/**
 * @deprecated Använd resolveTrackedUrl från lib/cta-resolver.ts istället.
 * Kvar för bakåtkompat, re-exporteras från cta-resolver. Använd inte direkt.
 */
export { buildSearchDeeplink, buildProductDeeplink } from '../lib/cta-resolver';
